export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"

export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS"
export const GET_JOBS = "GET_JOBS"
export const JOB_ERROR = "JOB_ERROR"

export const CREATE_APPLICANT_SUCCESS = "CREATE_APPLICANT_SUCCESS"
export const GET_APPLICANTS = "GET_APPLICANTS"
export const APPLICANT_ERROR = "JOB_ERROR"
